import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const scene=new THREE.Scene();
scene.background=new THREE.Color(0x8db8d8);scene.fog=new THREE.Fog(0x8db8d8,55,180);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,300);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x52606d,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(35,60,25);sun.castShadow=true;scene.add(sun);
function box(x,y,z,w,h,d,mat=0x6f7b86){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:mat,roughness:.78}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
box(0,-1,0,90,2,90,0x3f4952);box(0,9,-45,90,20,2,0x59636d);box(0,9,45,90,20,2,0x59636d);box(-45,9,0,2,20,90,0x59636d);box(45,9,0,2,20,90,0x59636d);
const plats=[[0,2,-10,14,2,10],[18,5,-3,10,2,9],[-20,4,12,12,2,12],[8,7,16,16,2,8],[-16,9,20,9,2,9],[28,2,23,10,2,10],[-29,2,-19,11,2,8],[28,9,-22,9,2,9]];plats.forEach(p=>box(...p,0x77828d));
const player=new THREE.Object3D();player.position.set(0,2.2,25);scene.add(player);camera.position.set(0,1.6,0);player.add(camera);
const keys={};let yaw=0,pitch=0,vy=0,locked=false,sliding=false,spaceWasDown=false,ctrlWasDown=false;
const walkSpeed=8,sprintSpeed=15,crouchSpeed=4.5,slideStartSpeed=17,gravity=24,jump=9.5,slideFriction=11,standingCameraY=1.6,crouchCameraY=.9;
let slideVelocity=new THREE.Vector3();

// Q: hızlı atılma
const dashMax=3;let dashCharges=3,dashVelocity=new THREE.Vector3(),dashTime=0,dashCooldown=0,dashRechargeTimer=0;const dashBars=document.querySelectorAll('.dash-bar');
function updateDashUI(){dashBars.forEach((b,i)=>b.classList.toggle('empty',i>=dashCharges))}updateDashUI();
function doDash(){if(!locked||dashCharges<=0||dashCooldown>0)return;dashCharges--;updateDashUI();dashTime=.24;dashCooldown=.28;dashRechargeTimer=0;const f=new THREE.Vector3(0,0,-1).applyQuaternion(camera.getWorldQuaternion(new THREE.Quaternion())).normalize();dashVelocity.copy(f).multiplyScalar(52);dashVelocity.y+=3.5;vy=0}
function updateDashRecharge(dt){if(dashCharges>=3){dashRechargeTimer=0;return}if(dashTime>0)return;dashRechargeTimer+=dt;const need=dashCharges===2?3:dashCharges===1?4:5;if(dashRechargeTimer>=need){dashCharges=3;dashRechargeTimer=0;updateDashUI()}}

// Space: çift zıplama, ikinci sıçrama 3 saniyede yenilenir
let doubleJumpReady=true,doubleJumpCooldown=0;function updateDoubleJump(dt){if(doubleJumpReady)return;doubleJumpCooldown=Math.max(0,doubleJumpCooldown-dt);if(doubleJumpCooldown<=0)doubleJumpReady=true}

// E: fantastik yukarı şok sıçraması
const boostBars=document.querySelectorAll('.boost-bar');let boostCharges=3,boostRechargeTimer=0,boostCooldown=0;function updateBoostUI(){boostBars.forEach((b,i)=>b.classList.toggle('empty',i>=boostCharges))}updateBoostUI();
function burstRing(pos){const ring=new THREE.Mesh(new THREE.TorusGeometry(.8,.07,8,28),new THREE.MeshBasicMaterial({color:0x6ee7ff,transparent:true,opacity:.9}));ring.position.copy(pos);ring.rotation.x=Math.PI/2;scene.add(ring);const born=performance.now();const tick=()=>{const a=(performance.now()-born)/360;if(a>=1){scene.remove(ring);ring.geometry.dispose();ring.material.dispose();return}ring.scale.setScalar(1+a*4);ring.material.opacity=.9*(1-a);requestAnimationFrame(tick)};tick()}
function doBoost(){if(!locked||boostCharges<=0||boostCooldown>0)return;boostCharges--;boostRechargeTimer=0;boostCooldown=.45;vy=Math.max(vy,18);burstRing(player.position)}
function updateBoostRecharge(dt){if(boostCharges>=3){boostRechargeTimer=0;return}boostRechargeTimer+=dt;if(boostRechargeTimer>=3){boostCharges=3;boostRechargeTimer=0;updateBoostUI()}}

// Fantastik arena hedefleri: gerçek kişi yerine hareketli enerji küreleri
const targets=[];let score=0,energy=100,energyRegen=0;const targetGroup=new THREE.Group();scene.add(targetGroup);
function makeTarget(x,y,z){const g=new THREE.Group();const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.72,2),new THREE.MeshStandardMaterial({color:0x7d5cff,emissive:0x3c1f99,emissiveIntensity:1.6,roughness:.3}));g.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.055,8,28),new THREE.MeshBasicMaterial({color:0x8ff7ff,transparent:true,opacity:.8}));g.add(ring);g.position.set(x,y,z);g.userData={home:new THREE.Vector3(x,y,z),phase:Math.random()*6.28,active:true};targetGroup.add(g);targets.push(g)}
[[0,3,-26],[18,7,-12],[-20,6,2],[8,9,28],[-28,4,16],[30,4,-8],[26,11,-25],[-5,5,4]].forEach(p=>makeTarget(...p));
const raycaster=new THREE.Raycaster();raycaster.far=90;const ndc=new THREE.Vector2(0,0);let waveCooldown=0;
function updateTargetMotion(t){targets.forEach((g,i)=>{if(!g.userData.active)return;g.position.y=g.userData.home.y+Math.sin(t*1.5+g.userData.phase)*.7;g.rotation.y=t*1.4+i;g.rotation.x=t*.7})}
function energyFlash(pos){const s=new THREE.Mesh(new THREE.SphereGeometry(.25,12,12),new THREE.MeshBasicMaterial({color:0xb8ffff,transparent:true,opacity:1}));s.position.copy(pos);scene.add(s);const born=performance.now();const tick=()=>{const a=(performance.now()-born)/280;if(a>=1){scene.remove(s);s.geometry.dispose();s.material.dispose();return}s.scale.setScalar(1+a*6);s.material.opacity=1-a;requestAnimationFrame(tick)};tick()}
function useEnergyWave(){if(!locked||waveCooldown>0||energy<20)return;energy-=20;waveCooldown=.38;raycaster.setFromCamera(ndc,camera);const hits=raycaster.intersectObjects(targets,true);let hit=null;for(const h of hits){let o=h.object;while(o.parent&&o.parent!==targetGroup)o=o.parent;if(o.parent===targetGroup&&o.userData.active){hit=o;break}}if(hit){hit.userData.active=false;score++;document.querySelector('#score').textContent=score;energyFlash(hit.position);hit.visible=false;setTimeout(()=>{hit.position.copy(hit.userData.home);hit.userData.active=true;hit.visible=true},850)}}
function updateEnergy(dt){energy=Math.min(100,energy+dt*7);const fill=document.querySelector('#energy-fill');const value=document.querySelector('#energy-value');fill.style.width=energy+'%';value.textContent=Math.round(energy)}

addEventListener('keydown',e=>{if(keys[e.code])return;keys[e.code]=true;if(e.code==='Space'||e.code==='ControlLeft'||e.code==='ControlRight')e.preventDefault();if(e.code==='KeyQ')doDash();if(e.code==='KeyE')doBoost();if(e.code==='KeyF')useEnergyWave()});addEventListener('keyup',e=>keys[e.code]=false);
const start=document.querySelector('#start-screen');start.addEventListener('click',()=>renderer.domElement.requestPointerLock());document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;start.classList.toggle('hidden',locked);if(!locked){dashTime=0;dashVelocity.set(0,0,0)}});document.addEventListener('mousemove',e=>{if(!locked)return;yaw-=e.movementX*.0022;pitch-=e.movementY*.0022;pitch=Math.max(-1.5,Math.min(1.5,pitch));player.rotation.y=yaw;camera.rotation.x=pitch});document.addEventListener('contextmenu',e=>e.preventDefault());

const clock=new THREE.Clock();function updateMovement(dt){const sprinting=keys.ShiftLeft||keys.ShiftRight,crouching=keys.ControlLeft||keys.ControlRight,ctrlPressed=crouching&&!ctrlWasDown,spacePressed=keys.Space&&!spaceWasDown;const dir=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(dir.lengthSq()){dir.normalize();dir.applyAxisAngle(new THREE.Vector3(0,1,0),yaw)}if(ctrlPressed&&sprinting&&dir.lengthSq()&&!sliding){slideVelocity.copy(dir).multiplyScalar(slideStartSpeed);sliding=true}
if(dashTime>0){dashTime=Math.max(0,dashTime-dt);player.position.addScaledVector(dashVelocity,dt);dashVelocity.multiplyScalar(Math.max(0,1-7*dt));vy-=gravity*.18*dt;player.position.y+=vy*dt}else{if(sliding){player.position.addScaledVector(slideVelocity,dt);const ns=Math.max(0,slideVelocity.length()-slideFriction*dt);if(ns===0){slideVelocity.set(0,0,0);sliding=false}else slideVelocity.setLength(ns)}else if(dir.lengthSq())player.position.addScaledVector(dir,(sprinting?sprintSpeed:(crouching?crouchSpeed:walkSpeed))*dt);vy-=gravity*dt;player.position.y+=vy*dt}
camera.position.y=THREE.MathUtils.lerp(camera.position.y,(crouching||sliding)?crouchCameraY:standingCameraY,Math.min(1,dt*14));player.position.x=Math.max(-41,Math.min(41,player.position.x));player.position.z=Math.max(-41,Math.min(41,player.position.z));let ground=0;const px=player.position.x,pz=player.position.z;for(const [x,y,z,w,dz] of plats)if(Math.abs(px-x)<w/2&&Math.abs(pz-z)<dz/2&&player.position.y>=y&&player.position.y<=y+2.5)ground=y+1.05;if(player.position.y<=ground){player.position.y=ground;if(vy<0)vy=0;if(spacePressed&&!crouching&&!sliding&&dashTime<=0)vy=jump}else if(spacePressed&&!crouching&&!sliding&&dashTime<=0&&doubleJumpReady){vy=jump;doubleJumpReady=false;doubleJumpCooldown=3}ctrlWasDown=crouching;spaceWasDown=keys.Space}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033);dashCooldown=Math.max(0,dashCooldown-dt);boostCooldown=Math.max(0,boostCooldown-dt);waveCooldown=Math.max(0,waveCooldown-dt);if(locked){updateMovement(dt);updateDashRecharge(dt);updateDoubleJump(dt);updateBoostRecharge(dt);updateEnergy(dt)}updateTargetMotion(clock.elapsedTime);renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});