import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const state={running:false,hp:100,level:1,gold:0,score:0,kills:0,weapon:'sword',enemies:[],keys:{},cool:{q:0,e:0},enemyTimer:0,wave:1};let scene,camera,renderer,player,last=0;
const $=id=>document.getElementById(id);function ui(){$('hp').textContent=Math.max(0,Math.round(state.hp));$('level').textContent=state.level;$('gold').textContent=state.gold;$('score').textContent=state.score;$('kills').textContent=state.kills;$('q').textContent=state.cool.q>0?state.cool.q.toFixed(1):'READY';$('e').textContent=state.cool.e>0?state.cool.e.toFixed(1):'READY'}
function addBox(x,y,z,px,py,pz,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat);m.position.set(px,py,pz);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
function makeUnit(color,isPlayer=false){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,5,10),new THREE.MeshStandardMaterial({color}));body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.42,12,8),new THREE.MeshStandardMaterial({color:0xd09a72}));head.position.y=1.05;head.castShadow=true;g.add(head);const sword=addBox(.14,.9,.14,.65,.2,0,new THREE.MeshStandardMaterial({color:0xc8c8c8,metalness:.7}));sword.rotation.z=-.2;g.add(sword);if(isPlayer){const shield=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.12,16),new THREE.MeshStandardMaterial({color:0x7a2f2f}));shield.rotation.z=Math.PI/2;shield.position.set(-.7,.1,0);g.add(shield)}g.userData={hp:isPlayer?100:40,isPlayer};return g}
function buildArena(){const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshStandardMaterial({color:0x4d4a3f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const wallMat=new THREE.MeshStandardMaterial({color:0x51473b});for(let i=-36;i<=36;i+=6){for(const z of[-36,36])addBox(5,5,6,i,2.5,z,wallMat);for(const x of[-36,36])addBox(6,5,5,x,2.5,i,wallMat)}for(let i=0;i<12;i++){const a=i*Math.PI/6;addBox(2,3,2,Math.cos(a)*15,1.5,Math.sin(a)*15,new THREE.MeshStandardMaterial({color:i%2?0x654c35:0x3f463e}))}}
function spawnEnemy(type='soldier'){const colors={soldier:0x9b3d32,archer:0x6f8c43,heavy:0x555b66,boss:0x5e2a70};const e=makeUnit(colors[type]||colors.soldier);const a=Math.random()*Math.PI*2,r=18+Math.random()*10;e.position.set(Math.cos(a)*r,1,Math.sin(a)*r);e.userData.type=type;e.userData.hp=type==='boss'?180:type==='heavy'?80:40;e.userData.speed=type==='boss'?1.2:type==='heavy'?1.5:2.2;e.userData.attack=0;scene.add(e);state.enemies.push(e)}
function hitEnemy(e,dmg){e.userData.hp-=dmg;state.score+=dmg*2;if(e.userData.hp<=0){scene.remove(e);state.enemies=state.enemies.filter(x=>x!==e);state.kills++;state.gold+=e.userData.type==='boss'?100:10;state.score+=100;if(state.kills%5===0){state.level++;state.hp=Math.min(100,state.hp+20)}}}
function attack(){if(!state.running)return;for(const e of[...state.enemies])if(e.position.distanceTo(player.position)<3.2)hitEnemy(e,state.weapon==='hammer'?35:25)}
function useAbility(k){if(state.cool[k]>0)return;if(k==='q'){attack();state.cool.q=4}else{state.hp=Math.min(100,state.hp+25);state.cool.e=8}}
function end(win){state.running=false;document.exitPointerLock?.();$('hud').classList.add('hidden');$('result').classList.remove('hidden');$('resultTitle').textContent=win?'ZAFER!':'YENİLDİN';$('resultText').textContent=`Skor: ${state.score} • Elemeler: ${state.kills} • Altın: ${state.gold} • Seviye: ${state.level}`}
function start(){ $('menu').classList.add('hidden');$('result').classList.add('hidden');$('hud').classList.remove('hidden');state.running=true;state.hp=100;state.score=0;state.kills=0;state.gold=0;state.level=1;state.wave=1;state.enemyTimer=3;state.enemies.forEach(e=>scene.remove(e));state.enemies=[];for(let i=0;i<5;i++)spawnEnemy(i===0?'archer':'soldier');ui()}
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x10151c);scene.fog=new THREE.Fog(0x10151c,35,100);camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,200);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.domElement.style.display='block';document.body.prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xc7d5ff,0x44301e,2));const sun=new THREE.DirectionalLight(0xffe0a0,3);sun.position.set(15,25,10);sun.castShadow=true;scene.add(sun);buildArena();player=makeUnit(0x3f73c8,true);player.position.set(0,1,12);scene.add(player);camera.position.set(0,4,18);addEvents();animate()}
function addEvents(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{state.keys[e.code]=true;if(e.code==='KeyR'&&!state.running)start();if(e.code==='KeyQ')useAbility('q');if(e.code==='KeyE')useAbility('e');if(e.code==='Digit1')state.weapon='sword';if(e.code==='Digit2')state.weapon='hammer'});addEventListener('keyup',e=>state.keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0)attack()});$('start').onclick=start;$('again').onclick=start;$('exit').onclick=()=>{$('result').classList.add('hidden');$('menu').classList.remove('hidden')};$('customize').onclick=()=>openModal('KARAKTER',`<div class="option"><b>Sınıflar</b>Şövalye • Viking • Okçu • Mızrakçı • Berserker</div><div class="option"><b>Zırhlar</b>Hafif • Orta • Ağır • Özel setler</div><div class="option"><b>Silahlar</b>Kılıç • Balta • Çekiç • Mızrak • Yay • Hançer</div>`);$('settings').onclick=()=>openModal('AYARLAR',`<div class="option"><b>Kontroller</b>WASD • Mouse • Sol tık • Q • E • Shift • R</div><div class="option"><b>Grafik</b>Gölge • Sis • Efekt yoğunluğu • FOV</div><div class="option"><b>Ses</b>Müzik • SFX • Ortam</div>`);$('close').onclick=()=>$('modal').classList.add('hidden')}
function animate(t=0){requestAnimationFrame(animate);const dt=Math.min(.033,(t-last)/1000||0);last=t;if(state.running){state.cool.q=Math.max(0,state.cool.q-dt);state.cool.e=Math.max(0,state.cool.e-dt);state.enemyTimer-=dt;const speed=state.keys.ShiftLeft?9:5;const v=new THREE.Vector3((state.keys.KeyD?1:0)-(state.keys.KeyA?1:0),0,(state.keys.KeyS?1:0)-(state.keys.KeyW?1:0));if(v.lengthSq()){v.normalize();player.position.addScaledVector(v,speed*dt);player.rotation.y=Math.atan2(v.x,v.z)}for(const e of[...state.enemies]){const d=e.position.distanceTo(player.position);if(d>2)e.position.addScaledVector(player.position.clone().sub(e.position).setY(0).normalize(),e.userData.speed*dt);else{e.userData.attack-=dt;if(e.userData.attack<=0){state.hp-=e.userData.type==='boss'?12:5;e.userData.attack=1}}}if(state.enemyTimer<=0){state.wave++;state.enemyTimer=4;const count=Math.min(8,2+state.wave);for(let i=0;i<count;i++)spawnEnemy(i%5===0?'heavy':'soldier');if(state.wave%5===0)spawnEnemy('boss')}if(state.hp<=0)end(false);if(state.kills>=25)end(true);ui();camera.position.lerp(new THREE.Vector3(player.position.x,player.position.y+4,player.position.z+7),.12);camera.lookAt(player.position.x,player.position.y+1,player.position.z)}renderer.render(scene,camera)}init();